version: 2.1

workflows:
  my-workflow:
    jobs:
      - build
      - deploy:
          context:
            - vs-resinvessel
          filters:
            branches:
              only:
                - main
      - version_compare:
          filters:
            branches:
              only:
                - /refs/pull\/.*\:main
      


jobs:
  build:
    machine: true
    steps:
      - checkout
      # - setup_remote_docker:
      #    docker_layer_caching: true
      # build Docker image
      - run: docker build -t trigrab/vs-resinvessel:$CIRCLE_BRANCH .
  version_compare:
    machine: true
    steps:
      - checkout
      - run: docker run trigrab/vs-resinvessel:$CIRCLE_BRANCH bash -c "cd /code && ci/isNewRelease.sh"
  deploy:
    machine: true
    steps:
      - checkout
      # - setup_remote_docker:
      #    docker_layer_caching: true
      # build Docker image
      - run: docker run trigrab/vs-resinvessel:$CIRCLE_BRANCH bash -c "/root/go/bin/ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} v\$(cat /release/version).${CIRCLE_BUILD_NUM} /ResinVessel.zip"
