version: 2.1

workflows:
  default-workflow:
    jobs:
      - build
      - deploy:
          context:
            - vs-resinvessel
          filters:
            branches:
              only:
                - main
          requires:
            - build
      - version_compare:
          filters:
            branches:
              ignore:
                - main
          requires:
            - build


jobs:
  build:
    machine: true
    steps:
      - checkout
      # - setup_remote_docker:
      #    docker_layer_caching: true
      # build Docker image
      - run: docker build -t trigrab/vs-resinvessel:$CIRCLE_BRANCH .
      - run: mkdir /tmp/docker
      - run: docker save -o /tmp/docker/vs-resinvessel trigrab/vs-resinvessel:$CIRCLE_BRANCH
      - persist_to_workspace:
          root: /tmp/docker
          paths:
           - vs-resinvessel

  version_compare:
    machine: true
    steps:
      - attach_workspace:
          at: /tmp/docker
      - run: docker load -i /tmp/docker/vs-resinvessel
      - run: docker run trigrab/vs-resinvessel:$CIRCLE_BRANCH bash -c "cd /code && chmod +x ci/isNewRelease.sh && ./ci/isNewRelease.sh"
  deploy:
    machine: true
    steps:
      - attach_workspace:
          at: /docker
      - run: docker load -i /docker/vs-resinvessel
      - run: docker run trigrab/vs-resinvessel:$CIRCLE_BRANCH bash -c "/root/go/bin/ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} v\$(cat /release/version) /ResinVessel.zip"
